# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcontacts' : '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/akonadi-search' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/kimap' : '@same'
    'pim/kmime' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/libkdepim' : '@same'
    'pim/libkleo' : '@same'
    'pim/messagelib' : '@same'
