# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcontacts' : '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'kde/pim/akonadi' : '@latest'
    'kde/pim/akonadi-contacts' : '@latest'
    'kde/pim/akonadi-mime' : '@latest'
    'kde/pim/akonadi-search' : '@latest'
    'kde/pim/calendarsupport' : '@latest'
    'kde/pim/kimap' : '@latest'
    'kde/pim/kmime' : '@latest'
    'kde/pim/kpimtextedit' : '@latest'
    'kde/pim/libkdepim' : '@latest'
    'kde/pim/libkleo' : '@latest'
    'kde/pim/messagelib' : '@latest'
